// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClickElement(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClickElement'](arg1, arg2, arg3);
}

export function ExecuteJavaScript(arg1, arg2) {
  return window['go']['main']['App']['ExecuteJavaScript'](arg1, arg2);
}

export function GetElementText(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetElementText'](arg1, arg2, arg3);
}

export function GetPageTitle(arg1) {
  return window['go']['main']['App']['GetPageTitle'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InputText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InputText'](arg1, arg2, arg3, arg4);
}

export function OpenBrowserAndScreenshot(arg1, arg2) {
  return window['go']['main']['App']['OpenBrowserAndScreenshot'](arg1, arg2);
}

export function SetHeadless(arg1) {
  return window['go']['main']['App']['SetHeadless'](arg1);
}

export function WaitForElement(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WaitForElement'](arg1, arg2, arg3, arg4);
}
