// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClickElement(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteJavaScript(arg1:string,arg2:string):Promise<string>;

export function GetElementText(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetPageTitle(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InputText(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function OpenBrowserAndScreenshot(arg1:string,arg2:string):Promise<string>;

export function SetHeadless(arg1:boolean):Promise<void>;

export function WaitForElement(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;
